# -*- coding: utf-8 -*-
"""gh_weather_data_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AcOIuqk0Uuk_AwfKsDrqTinamwv3VV8B
"""

import pandas as pd
from datetime import datetime
import random

# References for data ranges and climate patterns
# Max and Min Temperature: https://en.wikipedia.org/wiki/Climate_of_Ghana, https://www.statista.com/statistics/1263436/average-monthly-minimum-temperature-in-ghana/
# Rainfall: https://www.statista.com/statistics/1179259/average-monthly-rainfall-in-ghana/
# General Climate Patterns: https://climateknowledgeportal.worldbank.org/country/ghana/climate-data-historical, https://beautifulghana.com/seasons-in-ghana/

def generate_ghana_weather_data():
    # Define average data ranges for Ghana
    temp_max_base = (26.8, 31.6)  # Max Temperature (°C)
    temp_min_base = (20.66, 24.57)  # Min Temperature (°C)
    solar_radiation_base = (15, 25)  # Solar Radiation (MJ/m²-day)
    relative_humidity_base = (78, 87)  # Relative Humidity (%)
    wind_speed_base = (2, 6)  # Wind Speed (m/s)
    pressure_base = (1010, 1015)  # Estimated Atmospheric Pressure (hPa)

    # Monthly rainfall patterns
    monthly_rainfall = {
        "January": (9.53, 25),
        "February": (9.53, 25),
        "March": (25, 50),
        "April": (50, 100),
        "May": (100, 176.4),
        "June": (150, 176.4),
        "July": (100, 150),
        "August": (50, 100),
        "September": (50, 100),
        "October": (25, 50),
        "November": (9.53, 25),
        "December": (9.53, 25)
    }

    # Generate data for each month with variability
    weather_data = []
    for month, rainfall_range in monthly_rainfall.items():
        temp_variation = random.uniform(-1, 1)
        humidity_variation = random.uniform(-2, 2)
        wind_variation = random.uniform(-0.5, 0.5)
        pressure_variation = random.uniform(-2, 2)
        solar_variation = random.uniform(-2, 2)

        weather_data.append({
            "Month": month,
            "Max Temperature (°C)": round(random.uniform(*temp_max_base) + temp_variation, 2),
            "Min Temperature (°C)": round(random.uniform(*temp_min_base) + temp_variation, 2),
            "Average Rainfall (mm)": round(random.uniform(*rainfall_range), 2),
            "Relative Humidity (%)": round(random.uniform(*relative_humidity_base) + humidity_variation, 2),
            "Wind Speed (m/s)": round(random.uniform(*wind_speed_base) + wind_variation, 2),
            "Atmospheric Pressure (hPa)": round(random.uniform(*pressure_base) + pressure_variation, 2),
            "Solar Radiation (MJ/m²-day)": round(random.uniform(*solar_radiation_base) + solar_variation, 2)
        })

    return pd.DataFrame(weather_data)

# Generate and save the data
ghana_weather_data = generate_ghana_weather_data()
ghana_weather_data.to_csv('Ghana_Weather_Data.csv', index=False)
print("Ghana weather data generated and saved.")